type Sublog {
  id: String
  createdAt: String
  fileName: String
  category: String
  media: String
  title: String
  eyeCatchURL: String
  tag: [String]
  updatedAt: String
  body: String
}

type Query {
  getById(id: String): Sublog
  getAll: [Sublog]
  getByFileName(fileName: String): Sublog
  getByCategory(category: String): [Sublog]
}
